pipeline:
  build:
    image: fedora
    secrets: [access_token]
    when:
      branch: main
      event: [push, pull_request, tag]
    commands:
      - dnf install flatpak flatpak-builder -y
      - flatpak-builder --repo=repo --force-clean build build-aux/flatpak/io.github.Bavarder.Bavarder.json
      - flatpak build-bundle repo bavarder.flatpak io.github.Bavarder.Bavarder
      - ls -la
      