clone:
  git:
    image: bash
    commands:
      - cd /home/0xmrtt
      - if [ -d Bavarder ]; then
      -   cd Bavarder
      -   git pull
      - else
      -   git clone https://git.exozy.me/Bavarder/Bavarder.git
      - fi

pipeline:
  build:
    image: fish
    secrets: [ access_token, codeberg_token ]
    commands:
      - nix-env -iA nixpkgs.flatpak-builder
      - fish_add_path ~/.nix-profile/bin
      - cd /home/0xmrtt/Bavarder
      - flatpak-builder --repo=repo --force-clean build build-aux/flatpak/io.github.Bavarder.Bavarder.Devel.json
      - flatpak build-bundle repo bavarder.flatpak io.github.Bavarder.Bavarder.Devel
      - ls -la
      - curl --user 0xmrtt:$ACCESS_TOKEN --upload-file bavarder.flatpak "https://git.exozy.me/api/packages/$CI_REPO_OWNER/generic/$CI_REPO_NAME/$CI_BUILD_NUMBER/bavarder.flatpak"
      - curl --user 0xmrtt:$CODEBERG_TOKEN --upload-file bavarder.flatpak "https://codeberg.org/api/packages/$CI_REPO_OWNER/generic/$CI_REPO_NAME/$CI_BUILD_NUMBER/bavarder.flatpak"

  translate:
    image: fish
    commands:
      - nix-env -iA nixpkgs.gettext
      - fish_add_path ~/.nix-profile/bin
      - cd /home/0xmrtt/Bavarder
      - bash po/update-pot.sh
      - git add po/Bavarder.pot
      - git commit -m "Update"
      - git push origin main
    when:
      event: [manual]
