name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  flatpak:
    name: Flatpak
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-nightly
      options: --privileged
    strategy:
      matrix:
        arch: [x86_64]
      fail-fast: false
    steps:
      - name: Install Node.js
        run: dnf -y install nodejs
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          dnf -y install docker flatpak-builder flatpak git
          flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak remote-delete flathub-beta --force
          flatpak remote-add --if-not-exists gnome-nightly https://nightly.gnome.org/gnome-nightly.flatpakrepo
          flatpak install org.gnome.Sdk/x86_64/master -y
          flatpak install org.gnome.Platform/x86_64/master -y
      - name: Build
        run: |
          flatpak-builder --repo=repo --force-clean build build-aux/flatpak/io.github.Bavarder.Bavarder.json
          flatpak build-bundle repo bavarder.flatpak io.github.Bavarder.Bavarder
          ls -la
          echo "---${{ secrets.ACCESS_TOKEN }}---"
          curl --user 0xmrtt:${{ secrets.ACCESS_TOKEN }} --upload-file bavarder.flatpak https://git.projectsegfau.lt/api/packages/Bavarder/generic/Bavarder/$GITHUB_JOB/bavarder.flatpak          


