name: bavarder
base: core22 
adopt-info: bavarder
grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64

layout:
  /usr/lib/x86_64-linux-gnu/webkitgtk-6.0:
    bind: $SNAP/webkitgtk-platform/usr/lib/x86_64-linux-gnu/webkitgtk-6.0

parts:
  blueprint-compiler:
    source: https://gitlab.gnome.org/jwestman/blueprint-compiler.git
    source-tag: 'v0.8.1'
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    override-prime: ''      
  gpt4all:
    source: https://github.com/nomic-ai/gpt4all.git
    source-commit: '39acbc837816ea9c7673bfe5cf83aeaed95b2c5f'
    plugin: python
    override-build: |
      craftctl default
      pip install --prefix=$CRAFT_PART_INSTALL/usr gpt4all
      sed -i '1c#!/usr/bin/python3' -i $CRAFT_PART_INSTALL/usr/local/bin/*
    python-packages:
      - certifi==2023.7.22
      - charset-normalizer==3.2.0
      - idna==3.4
      - requests==2.31.0
      - urllib3==2.0.4
      - tqdm==4.66.1
      - Babel==2.12.1
      - openai==0.27.8
      - aiohttp==3.8.5
      - aiosignal==1.3.1
      - async-timeout==4.0.3
      - attrs==23.1.0
      - frozenlist==1.4.0
      - multidict==6.0.4
      - yarl==1.9.2
      - lxml
    organize: 
      bin: usr/bin
      lib/python3.10/site-packages: usr/lib/python3/dist-packages
      usr/local/bin: usr/bin
      usr/local/lib/python3.10/dist-packages: usr/lib/python3/dist-packages      
    prime:
      - -usr/bin/activate*
      - -usr/bin/Activate.ps1
      - -usr/bin/python*
      - -usr/bin/pip*
      - -include
      - -lib
      - -lib64
      - -bin
      - -share
      - -pyvenv.cfg

  bavarder:
    after: [blueprint-compiler, gpt4all]
    plugin: meson
    source: https://codeberg.org/Bavarder/Bavarder.git
    source-tag: '1.0.0'
    meson-parameters:
      - --prefix=/snap/bavarder/current/usr
      - -Dbuildtype=release
    build-snaps:
      - webkitgtk-6-gnome-2204-sdk/latest/stable
    build-environment:
      - LD_LIBRARY_PATH: /snap/webkitgtk-sdk/current/usr/lib:/snap/webkitgtk-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET:/snap/webkitgtk-sdk/current/usr/lib/webkitgtk-6.0:/snap/webkitgtk-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0:$LD_LIBRARY_PATH
      - PYTHONPATH: $CRAFT_STAGE/lib/python3/site-packages:$CRAFT_STAGE/lib/python3.10/site-packages:$CRAFT_STAGE/usr/lib/python3/dist-packages:$PYTHONPATH 
      - GI_TYPELIB_PATH: /snap/gnome-42-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0:/snap/gnome-42-2204-sdk/current/usr/lib/girepository-1.0:/snap/webkitgtk-6-gnome-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0 
    override-build: |
      set -eux
      craftctl default
      sed -e '1c#!/usr/bin/env python3' -i $CRAFT_PART_INSTALL/snap/bavarder/current/usr/bin/bavarder
      chmod +x $CRAFT_PART_INSTALL/snap/bavarder/current/usr/bin/bavarder      
    parse-info: [usr/share/appdata/io.github.Bavarder.Bavarder.appdata.xml]
    organize:
      snap/bavarder/current: .
    prime:
      - -snap/bavarder

  gst:
    after: [ bavarder ]
    plugin: nil
    stage-packages:
      - gir1.2-gstreamer-1.0
    prime:
      - usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0/Gst-1.0.typelib
      - usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0/GstBase-1.0.typelib
      - usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0/GstCheck-1.0.typelib
      - usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0/GstController-1.0.typelib
      - usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0/GstNet-1.0.typelib

plugs:
  webkitgtk-6-gnome-2204:
    interface: content
    target: $SNAP/webkitgtk-platform
    default-provider: webkitgtk-6-gnome-2204

slots:
  bavarder:
    interface: dbus
    bus: session
    name: io.github.Bavarder.Bavarder

apps:
  bavarder:
    command: usr/bin/bavarder
    extensions: [gnome]
    common-id: io.github.Bavarder.Bavarder
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
      GI_TYPELIB_PATH: $SNAP/webkitgtk-platform/usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0:$GI_TYPELIB_PATH
      LD_LIBRARY_PATH: $SNAP/webkitgtk-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/webkitgtk-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkitgtk-6.0:$LD_LIBRARY_PATH
    plugs:
      - network
      - network-status
      - network-bind
      - unity7
