name: bavarder
base: core22 
adopt-info: bavarder
grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64

layout:
  /usr/lib/x86_64-linux-gnu/webkitgtk-6.0:
    bind: $SNAP/webkitgtk-platform/usr/lib/x86_64-linux-gnu/webkitgtk-6.0

parts:
  blueprint-compiler:
    source: https://gitlab.gnome.org/jwestman/blueprint-compiler.git
    source-tag: 'v0.8.1'
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    override-prime: ''      
  bavarder:
    after: [blueprint-compiler]
    plugin: meson
    source: https://codeberg.org/Bavarder/Bavarder.git
    source-tag: '1.0.0'
    meson-parameters:
      - --prefix=/snap/bavarder/current/usr
      - -Dbuildtype=release
    build-snaps:
      - webkitgtk-6-gnome-2204-sdk/latest/stable
    build-environment:
      - LD_LIBRARY_PATH: /snap/webkitgtk-sdk/current/usr/lib:/snap/webkitgtk-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET:/snap/webkitgtk-sdk/current/usr/lib/webkitgtk-6.0:/snap/webkitgtk-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0:$LD_LIBRARY_PATH
      - PYTHONPATH: $CRAFT_STAGE/lib/python3/site-packages:$CRAFT_STAGE/lib/python3.10/site-packages:$CRAFT_STAGE/usr/lib/python3/dist-packages:$PYTHONPATH 
      - GI_TYPELIB_PATH: /snap/gnome-42-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0:/snap/gnome-42-2204-sdk/current/usr/lib/girepository-1.0:/snap/webkitgtk-6-gnome-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0 
    override-build: |
      set -eux
      craftctl default
      sed -e '1c#!/usr/bin/env python3' -i $CRAFT_PART_INSTALL/snap/bavarder/current/usr/bin/bavarder
      chmod +x $CRAFT_PART_INSTALL/snap/bavarder/current/usr/bin/bavarder      
    parse-info: [usr/share/appdata/io.github.Bavarder.Bavarder.appdata.xml]
    organize:
      snap/bavarder/current: .
    prime:
      - -snap/bavarder

  gst:
    after: [ bavarder ]
    plugin: nil
    stage-packages:
      - gir1.2-gstreamer-1.0
    prime:
      - usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0/Gst-1.0.typelib
      - usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0/GstBase-1.0.typelib
      - usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0/GstCheck-1.0.typelib
      - usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0/GstController-1.0.typelib
      - usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0/GstNet-1.0.typelib

plugs:
  webkitgtk-6-gnome-2204:
    interface: content
    target: $SNAP/webkitgtk-platform
    default-provider: webkitgtk-6-gnome-2204

slots:
  bavarder:
    interface: dbus
    bus: session
    name: io.github.Bavarder.Bavarder

apps:
  bavarder:
    command: usr/bin/bavarder
    extensions: [gnome]
    common-id: io.github.Bavarder.Bavarder
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
      GI_TYPELIB_PATH: $SNAP/webkitgtk-platform/usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0:$GI_TYPELIB_PATH
      LD_LIBRARY_PATH: $SNAP/webkitgtk-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/webkitgtk-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkitgtk-6.0:$LD_LIBRARY_PATH
    plugs:
      - network
      - network-status
      - network-bind
      - unity7
